### PR TITLE
fix dropdown seed list border, scrollview and error message

### LINKED ISSUE #355: Seed restore page issues
- Drop down white background color clashes with the background. Should have a border or drop shadow like android has to make the drop down menu easy to distinguish from the background. 
- Drop down should always drop down and no drop up..only below.
- Window is auto scrolling as the user inputs words, but their input should be just above the keyboard rather then in the middle of the viewable area.
- Error is showing for not all words entered by the time the user gets to the bottom of the screen. This error should only appear if they try and hit the confirm button and the words are not all filled in.

### PR DESCRIPTION
**Pull request by macsleven**
closes #355

### CODE REVIEW

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 1]
```diff
@@ -34,6 +34,10 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
         registerObserverForKeyboardNotification()
         self.hideKeyboardWhenTappedAround()
         
+        //set border for dropdown list
+        self.wordSelectionDropDownContainer.layer.borderWidth = 1
+        self.wordSelectionDropDownContainer.layer.borderColor = UIColor(red:222/255, green:225/255, blue:227/255, alpha: 1).cgColor
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: - Can this be translated to hex? It's simpler to read.
- Create a variable for this color in the `UIColor.swift` file to ensure that no other similar color exists already and that it isn't recreated subsequently if someone needs to use this same color.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 2]
```diff
@@ -63,16 +67,19 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
                                      y: self.view.frame.origin.y,
                                      width: self.view.frame.width,
                                      height: window.origin.y + window.height - keyboardSize.height)
+            self.tableView.contentInset = UIEdgeInsets(top: 0,left: 0,bottom: 10,right: 0)
         }
     }
     
+
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: Why do we need this additional empty line space?

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 3]
```diff
@@ -63,16 +67,19 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
                                      y: self.view.frame.origin.y,
                                      width: self.view.frame.width,
                                      height: window.origin.y + window.height - keyboardSize.height)
+            self.tableView.contentInset = UIEdgeInsets(top: 0,left: 0,bottom: 10,right: 0)
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: - Add an empty line space before this, code looks too clogged.
- Add a comment to show why this is necessary.
- Use whitespace to separate the function call parameters.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 4]
```diff
@@ -111,55 +118,48 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
     }
     
     func focusSeedWordInput(at tableRowIndex: Int) {
         let tableIndexPath = IndexPath(row: tableRowIndex, section: 0)
-        
         let nextSeedWordCell = self.tableView.cellForRow(at: tableIndexPath) as? RecoveryWalletSeedWordCell
         nextSeedWordCell?.seedWordAutoComplete.becomeFirstResponder()
         
-        self.tableView.scrollToRow(at: tableIndexPath, at: .middle, animated: true)
+        self.tableView.scrollToRow(at: tableIndexPath, at: .bottom, animated: true)
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: What if you don't scroll? I mean, if you take off this line completely.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 5]
```diff
@@ -111,55 +118,48 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
     
     @IBAction func backButtonTap(_ sender: Any) {
         self.navigationController?.popViewController(animated: true)
     }
     
     @IBAction func onConfirm() {
-        let validatedSeed = self.validateSeed()
-        if validatedSeed.valid {
-            self.secureWallet(validatedSeed.seed)
+        self.lblEnterAllSeeds.isHidden = false
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: Shouldn't you only display this label if there's an error?

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 6]
```diff
@@ -111,55 +118,48 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
         if self.validateSeed().valid {
             self.activateConfirmButton()
         } else {
-            self.deactivateConfirmButton()
+            self.deactivateConfirmButtonForError()
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: Why is the function renamed? If the seed is not valid, deactivate confirm button, that seem straightforward to me. What is deactivate confirm button for error?

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 7]
```diff
@@ -101,7 +108,7 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
     
     func seedWordEntered(for wordIndex: Int, seedWord: String, moveToNextField: Bool) {
         self.userEnteredSeedWords[wordIndex] = seedWord
-        
+        self.lblEnterAllSeeds.isHidden = true
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: - Add an empty line space after this
- If the view was visible and you hide it, there's a weird space that shows up. You need to do this:
```
// increase top spacing since warning label is now hidden so as to position button in center
        self.tableViewFooterTopSpacingConstraint.constant = 30
        UIView.animate(withDuration: 0.5) {
            self.tableViewFooter.layoutIfNeeded()
        }
```

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 8]
```diff
@@ -111,55 +118,48 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
+    func deactivateConfirmButtonForError(){
+         self.btnConfirm.backgroundColor = UIColor.appColors.lightGray
         
         // reduce top spacing so that warning label and confirm button are centered in display
         self.tableViewFooterTopSpacingConstraint.constant = 10
         UIView.animate(withDuration: 0.5) {
             self.tableViewFooter.layoutIfNeeded()
         }
     }
+    func activateConfirmButton() {
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: Please maintain the initial function order: `activateConfirmButton` before `deactivateConfirmButton`.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 9]
```diff
@@ -111,55 +118,48 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
-    func deactivateConfirmButton() {
-        self.btnConfirm.backgroundColor = UIColor.appColors.lightGray
-        self.lblEnterAllSeeds.isHidden = false
-        
-        if self.userEnteredSeedWords.contains("") {
-            self.lblEnterAllSeeds.text = "Not all seeds are entered. Please, check input fields and enter all seeds."
-        } else {
-            self.lblEnterAllSeeds.text = "You entered an incorrect seed. Please check your words."
-        }
+    func deactivateConfirmButtonForError(){
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: Space before opening brace please.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift (hunk 4 above)
Comment (macsleven) [reply decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: Scrolling keeps the input textfield just below the keyboard input even if the user scrolls up and continue input.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift (hunk 5 above)
Comment (macsleven) [reply decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: it displays only if there is an error

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift (hunk 7 above)
Comment (macsleven) [reply decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: There is no weird space showing up

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift (hunk 6 above)
Comment (macsleven) [reply decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: the button is not  really deactivated it blocks it from proceeding and display the appropriate error message when clicked.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 10]
```diff
@@ -101,6 +109,13 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
     
     func seedWordEntered(for wordIndex: Int, seedWord: String, moveToNextField: Bool) {
         self.userEnteredSeedWords[wordIndex] = seedWord
+        self.lblEnterAllSeeds.isHidden = true
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: Enclose lines 112 to 118 in an if statement. There's especially no need to call `UIView.animate` if nothing is being changed on the UI. Should first check that `self.lblEnterAllSeeds.isHidden == false`

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 11]
```diff
@@ -111,55 +126,50 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
         if self.validateSeed().valid {
             self.activateConfirmButton()
         } else {
-            self.deactivateConfirmButton()
+            self.deactivateConfirmButtonForError()
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: > the button is not really deactivated it blocks it from proceeding and display the appropriate error message when clicked.

We have a `activateConfirmButton` function, that does not "really" activate the button either, it just changes the background color. But the name makes more sense, so does `deactivateConfirmButton`.

UPDATE:
I see that both functions now only change the button color. We can take off those functions and set the appropriate colors directly instead of calling those functions. Unless the functions are called from more than 1 place each.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 12]
```diff
@@ -111,55 +126,50 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
     }
     
     func focusSeedWordInput(at tableRowIndex: Int) {
         let tableIndexPath = IndexPath(row: tableRowIndex, section: 0)
-        
         let nextSeedWordCell = self.tableView.cellForRow(at: tableIndexPath) as? RecoveryWalletSeedWordCell
         nextSeedWordCell?.seedWordAutoComplete.becomeFirstResponder()
         
-        self.tableView.scrollToRow(at: tableIndexPath, at: .middle, animated: true)
+        self.tableView.scrollToRow(at: tableIndexPath, at: .bottom, animated: true)
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: Is there a need to "always" move the user to the bottom? Android doesn't do this. I don't think the issue meant that the app should always scroll to the bottom but just like android, at some point the user will be taken to the bottom naturally.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 13]
```diff
@@ -111,55 +126,50 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
     }
     
     @IBAction func onConfirm() {
-        let validatedSeed = self.validateSeed()
-        if validatedSeed.valid {
-            self.secureWallet(validatedSeed.seed)
+        self.lblEnterAllSeeds.isHidden = false
+        
+        // reduce top spacing so that warning label and confirm button are centered in display
+        self.tableViewFooterTopSpacingConstraint.constant = 10
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: This should not always be done when the user taps confirm button, but only if there's an error to display. This can go into a function `displaySeedError(_ errorMessage: String)`. Set the error label text there and do this animation. Of course, you'd only call that function if there's an error to display.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 14]
```diff
@@ -63,6 +67,9 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
                                      y: self.view.frame.origin.y,
                                      width: self.view.frame.width,
                                      height: window.origin.y + window.height - keyboardSize.height)
+            
+            // adjust focus seed word input just above the keyboard
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: This does not adjust the focused seed word input or any input for that matter. It creates space between the bottom of the table and the top of the keyboard. A better comment would be:
`// add space between bottom of table and top of keyboard`

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 15]
```diff
@@ -73,6 +80,7 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
                                      y: self.view.frame.origin.y,
                                      width: self.view.frame.width,
                                      height: window.origin.y + window.height)
+             self.tableView.contentInset = UIEdgeInsets(top: 0,left: 0,bottom: 0,right: 0)
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: Add an empty line space and the following comment before this line:
`// remove space at the bottom of table that was added when keyboard was displayed`

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift (hunk 12 above)
Comment (macsleven) [reply decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: please check the issue created for it and it works accordingly

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift (hunk 14 above)
Comment (macsleven) [reply decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: the space is meant to adjust the view

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift (hunk 13 above)
Comment (macsleven) [reply decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: ok

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 16]
```diff
@@ -109,57 +126,48 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
     func focusSeedWordInput(at tableRowIndex: Int) {
         let tableIndexPath = IndexPath(row: tableRowIndex, section: 0)
-        
         let nextSeedWordCell = self.tableView.cellForRow(at: tableIndexPath) as? RecoveryWalletSeedWordCell
         nextSeedWordCell?.seedWordAutoComplete.becomeFirstResponder()
         
-        self.tableView.scrollToRow(at: tableIndexPath, at: .middle, animated: true)
+        self.tableView.scrollToRow(at: tableIndexPath, at: .bottom, animated: true)
     }
+
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: This empty line space is unnecessary.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 17]
```diff
@@ -109,57 +126,48 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
-        UIView.animate(withDuration: 0.5) {
-            self.tableViewFooter.layoutIfNeeded()
-        }
+    @IBAction func backButtonTap(_ sender: Any) {
+        self.navigationController?.popViewController(animated: true)
     }
-    
-    func deactivateConfirmButton() {
-        self.btnConfirm.backgroundColor = UIColor.appColors.lightGray
+    func displayErrorLabel(){
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: - This function should appear after the `confirm` function below, this function is called by that function.
- There should be a space before the opening brace.
- This function is not yet as intended, it should take a parameter of the error text to display, and also perform the animation (`UIView.animate`):
```
This should not always be done when the user taps confirm button, but only if there's an error to display. This can go into a function displaySeedError(_ errorMessage: String). Set the error label text there and do this animation. Of course, you'd only call that function if there's an error to display.
```

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 18]
```diff
@@ -101,6 +111,13 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
     
     func seedWordEntered(for wordIndex: Int, seedWord: String, moveToNextField: Bool) {
         self.userEnteredSeedWords[wordIndex] = seedWord
+        self.lblEnterAllSeeds.isHidden = true
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: This comment is not resolved:

> Enclose lines 112 to 118 in an if statement. There's especially no need to call UIView.animate if nothing is being changed on the UI. Should first check that self.lblEnterAllSeeds.isHidden == false

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 19]
```diff
@@ -109,57 +126,48 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
     }
     
     func focusSeedWordInput(at tableRowIndex: Int) {
         let tableIndexPath = IndexPath(row: tableRowIndex, section: 0)
-        
         let nextSeedWordCell = self.tableView.cellForRow(at: tableIndexPath) as? RecoveryWalletSeedWordCell
         nextSeedWordCell?.seedWordAutoComplete.becomeFirstResponder()
         
-        self.tableView.scrollToRow(at: tableIndexPath, at: .middle, animated: true)
+        self.tableView.scrollToRow(at: tableIndexPath, at: .bottom, animated: true)
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: > The default behaviour is to change the scroll position only if the next seed word field is out of view.

I think removing this line of code will produce the expected behaviour described above.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 20]
```diff
@@ -102,65 +112,65 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
-            self.tableViewFooter.layoutIfNeeded()
-        }
+
+    @IBAction func backButtonTap(_ sender: Any) {
+        self.navigationController?.popViewController(animated: true)
     }
     
-    func deactivateConfirmButton() {
-        self.btnConfirm.backgroundColor = UIColor.appColors.lightGray
+    func displayErrorLabel(){
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: Is this function called anywhere? Please delete.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 21]
```diff
@@ -102,65 +112,59 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
         
-        if self.userEnteredSeedWords.contains("") {
-            self.lblEnterAllSeeds.text = "Not all seeds are entered. Please, check input fields and enter all seeds."
-        } else {
-            self.lblEnterAllSeeds.text = "You entered an incorrect seed. Please check your words."
-        }
-        
         // reduce top spacing so that warning label and confirm button are centered in display
         self.tableViewFooterTopSpacingConstraint.constant = 10
-        UIView.animate(withDuration: 0.5) {
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: This is required when changing the `tableViewFooterTopSpacingConstraint`. Please restore it.

File: decred_wallet/Constants/Constants.swift [hunk 22]
```diff
@@ -30,6 +30,7 @@ struct GlobalConstants {
         static let orangeColor = UIColor(hex: "fd714a")
         static let navigationBarColor = UIColor(hex: "689F38")
         static let lightGrey = UIColor(red: 236.0/255.0, green: 238.0/255.0, blue: 241.0/255.0, alpha: 1.0)
+        static let BorderlightGrey = UIColor(red:222/255, green:225/255, blue:227/255, alpha: 1)
```
Comment (itswisdomagain) [inline decred_wallet/Constants/Constants.swift]: - This should go to `Extensions/UIColor.swift`. See the comment above this `Colors` struct.
- Color names should not include where they're used as though they can't be used elsewhere. Take off the `Border` text from the variable name and describe the color alone. We already have `lightGrey`, so one can be `lighterGrey` and the other `lightGrey`.
- Variable name should start with small letter.
- Use hex code for the color please.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 23]
```diff
@@ -34,6 +34,10 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
         registerObserverForKeyboardNotification()
         self.hideKeyboardWhenTappedAround()
         
+        //set border for dropdown list
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: there should be a single whitespace between the last slash and the first word in the comment
`// set ...`

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 24]
```diff
@@ -102,65 +112,62 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
-        
-        // increase top spacing since warning label is now hidden so as to position button in center
-        self.tableViewFooterTopSpacingConstraint.constant = 30
-        UIView.animate(withDuration: 0.5) {
-            self.tableViewFooter.layoutIfNeeded()
+    @IBAction func onConfirm() {
+        if self.userEnteredSeedWords.contains("") {
+            self.displaySeedError("Not all seeds are entered. Please, check input fields and enter all seeds.")
+        }
+        else{
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: - `else` should be in previous line
- there should be single whitespace before opening brace:

`} else {`

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 25]
```diff
@@ -102,65 +112,62 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
+            else {
+                self.displaySeedError("You entered an incorrect seed. Please check your words.")
+            }
         }
     }
     
-    func deactivateConfirmButton() {
-        self.btnConfirm.backgroundColor = UIColor.appColors.lightGray
+    func displaySeedError(_ errorMessage: String) {
         self.lblEnterAllSeeds.isHidden = false
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: - Generally a better idea to set the text before making the view visible
- Refactor/rename this label to `invalidSeedLabel`, it obviously no longer only deal with cases where all seed words are not entered.

File: decred_wallet/Extensions/UIColor.swift [hunk 26]
```diff
@@ -15,11 +15,10 @@ extension UIColor {
         static let decredBlue = UIColor.init(hex: "#2970FF")
         static let decredGreen = UIColor.init(hex: "#41BF53")
         static let decredOrange = UIColor.init(hex: "#ED6D47")
-        
         static let darkYellowWarning = UIColor.init(hex: "#E7C659")
         static let green = UIColor.init(hex: "#2DD8A3")
-//        static let gray = UIColor(red: 132.0/255.0, green: 139.0/255.0, blue: 144.0/255.0, alpha: 1.0)
-        static let lightGray = UIColor.init(hex: "#C4CBD2")
+        static let lightGray = UIColor.init(hex: "DEE1E3")
```
Comment (itswisdomagain) [inline decred_wallet/Extensions/UIColor.swift]: Add the "#" to maintain uniformity with the rest of the code.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 27]
```diff
@@ -146,28 +146,27 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
     
     @IBAction func onConfirm() {
         if self.userEnteredSeedWords.contains("") {
-            self.displaySeedError("Not all seeds are entered. Please, check input fields and enter all seeds.")
-        }
-        else{
+            self.invalidSeedLabel("Not all seeds are entered. Please, check input fields and enter all seeds.")
+        }else{
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: whitespace before and after `else`

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 28]
```diff
@@ -146,28 +146,27 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
             else {
-                self.displaySeedError("You entered an incorrect seed. Please check your words.")
+                self.invalidSeedLabel("You entered an incorrect seed. Please check your words.")
             }
         }
     }
     
-    func displaySeedError(_ errorMessage: String) {
-        self.lblEnterAllSeeds.isHidden = false
+    func invalidSeedLabel(_ errorMessage: String) {
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: This space can go.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 29]
```diff
@@ -146,28 +146,27 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: `displaySeedError` is a fine function name, I meant to rename the `lblEnterAllSeeds` label.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 30]
```diff
@@ -146,28 +146,27 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
         
         // reduce top spacing so that warning label and confirm button are centered in display
         self.tableViewFooterTopSpacingConstraint.constant = 10
         UIView.animate(withDuration: 0.5) {
             self.tableViewFooter.layoutIfNeeded()
         }
         self.lblEnterAllSeeds.text = errorMessage
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: An empty line space can be added before this line.

File: decred_wallet/Features/Wallet Setup/WalletSetup.storyboard [hunk 31]
```diff
@@ -78,7 +78,7 @@
                                                         <rect key="frame" x="27.5" y="54.5" width="124.5" height="54.5"/>
                                                         <fontDescription key="fontDescription" name="SourceSansPro-Regular" family="Source Sans Pro" pointSize="15"/>
                                                         <color key="textColor" red="0.28235294119999998" green="0.33725490200000002" blue="0.43137254899999999" alpha="1" colorSpace="calibratedRGB"/>
-                                                        <nil key="highlightedColor"/>
+                                                        <color key="highlightedColor" red="0.87058823529411766" green="0.88235294117647056" blue="0.8901960784313725" alpha="1" colorSpace="calibratedRGB"/>
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/WalletSetup.storyboard]: Probably need to undo this change.

File: decred_wallet/Constants/Constants.swift (hunk 22 above)
Comment (itswisdomagain) [inline decred_wallet/Constants/Constants.swift]: This can now be deleted.

File: decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift [hunk 32]
```diff
@@ -102,65 +110,59 @@ class RecoverExistingWalletViewController: WalletSetupBaseViewController, UITabl
...
-        self.btnConfirm.backgroundColor = UIColor.appColors.lightGray
-        self.lblEnterAllSeeds.isHidden = false
-        
+    @IBAction func onConfirm() {
         if self.userEnteredSeedWords.contains("") {
-            self.lblEnterAllSeeds.text = "Not all seeds are entered. Please, check input fields and enter all seeds."
-        } else {
-            self.lblEnterAllSeeds.text = "You entered an incorrect seed. Please check your words."
+            self.displaySeedError("Not all seeds are entered. Please, check input fields and enter all seeds.")
+        } else{
```
Comment (itswisdomagain) [inline decred_wallet/Features/Wallet Setup/RecoverExistingWalletViewController.swift]: This should not require multiple reviews to correct. Please add a whitespace before the opening brace.
