### PR TITLE
Fix crash on PIN display for send and add account

### LINKED ISSUE #374: app crash on send fund and add account
App crash when the PIN controller is called  for Authentication on send fund, add account, security menu(sign message) and delete wallet

### PR DESCRIPTION
**Pull request by macsleven**
closes #374 
Fix crash on PIN display for send ,add account, security menu(sign menu) and settings(delete wallet)

### CODE REVIEW

File: decred_wallet/view_controller/AddAcountViewController.swift [hunk 1]
```diff
@@ -37,7 +37,8 @@ class AddAcountViewController: UIViewController {
             if SpendingPinOrPassword.currentSecurityType() == SecurityViewController.SECURITY_TYPE_PASSWORD {
                 addAccountWithoutPin()
             }else{
-                let requestPinVC = storyboard!.instantiateViewController(withIdentifier: "RequestPinViewController") as! RequestPinViewController
+                let storyboard2 =  UIStoryboard(name: "Security", bundle: nil)
+                let requestPinVC = storyboard2.instantiateViewController(withIdentifier: "RequestPinViewController") as! RequestPinViewController
```
Comment (itswisdomagain) [inline decred_wallet/view_controller/AddAcountViewController.swift]: Use `let requestPinVC = RequestPinViewController.instantiate()`.
